passes:
  - mem2reg
  - sroa
  - instcombine
  - aggressive-instcombine
  - instsimplify
  - simplifycfg
  - early-cse
  - dce
  - adce
  - bdce
  - reassociate
  - gvn
  - jump-threading
  - correlated-propagation
