passes:
  - name: mem2reg
    pipeline: mem2reg
    category: scalar
    stage: v1
  - name: sroa
    pipeline: sroa
    category: scalar
    stage: v1
  - name: instcombine
    pipeline: instcombine
    category: scalar
    stage: v1
  - name: aggressive-instcombine
    pipeline: aggressive-instcombine
    category: scalar
    stage: v1
  - name: instsimplify
    pipeline: instsimplify
    category: scalar
    stage: v1
  - name: simplifycfg
    pipeline: simplifycfg
    category: cfg
    stage: v1
  - name: early-cse
    pipeline: early-cse
    category: scalar
    stage: v1
  - name: dce
    pipeline: dce
    category: cleanup
    stage: v1
  - name: adce
    pipeline: adce
    category: cleanup
    stage: v1
  - name: bdce
    pipeline: bdce
    category: cleanup
    stage: v1
  - name: reassociate
    pipeline: reassociate
    category: scalar
    stage: v1
  - name: gvn
    pipeline: gvn
    category: memory
    stage: v1
  - name: jump-threading
    pipeline: jump-threading
    category: cfg
    stage: v1
  - name: correlated-propagation
    pipeline: correlated-propagation
    category: cfg
    stage: v1
  - name: sccp
    pipeline: sccp
    category: scalar
    stage: v2
  - name: dse
    pipeline: dse
    category: memory
    stage: v2
  - name: memcpyopt
    pipeline: memcpyopt
    category: memory
    stage: v2
  - name: sink
    pipeline: sink
    category: cfg
    stage: v2
  - name: tailcallelim
    pipeline: tailcallelim
    category: scalar
    stage: v2
  - name: loop-simplify
    pipeline_candidates:
      - loop-simplify
      - function(loop-simplify)
    category: loop
    stage: v3
  - name: lcssa
    pipeline_candidates:
      - lcssa
      - function(lcssa)
    category: loop
    stage: v3
  - name: loop-rotate
    pipeline_candidates:
      - loop-rotate
      - loop(loop-rotate)
      - function(loop(loop-rotate))
    category: loop
    stage: v3
  - name: licm
    pipeline_candidates:
      - licm
      - loop(licm)
      - function(loop(licm))
      - function(loop-mssa(licm))
    category: loop
    stage: v3
  - name: indvars
    pipeline_candidates:
      - indvars
      - loop(indvars)
      - function(loop(indvars))
    category: loop
    stage: v3
  - name: loop-deletion
    pipeline_candidates:
      - loop-deletion
      - loop(loop-deletion)
      - function(loop(loop-deletion))
    category: loop
    stage: v3
